database:
  image: postgres:9
  volumes:
    - ./persistent/data:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=SumPassw0rdHere
    - POSTGRES_DB=postgres
  restart: unless-stopped

postgres-backup:
  image: .
  container_name: postgres-backup
  links:
    - database:db # Maps as "db"
  environment:
    - PGUSER=postgres
    - PGPASSWORD=SumPassw0rdHere
    - CRON_SCHEDULE=* * * * * # Every minute
    - RETAIN_COUNT=5 # Keep this number of backups
    - PGDB=postgres # The name of the database to dump
  #  - PGHOST=db # The hostname of the PostgreSQL database to dump
  volumes:
    - ./persistent/dump
